name: development-staking -> development
on:
  push:
    branches:
      - development-staking

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.REPO_SYNC_TOKEN}}
          FROM_BRANCH: "development-staking"
          TO_BRANCH: "development"
